### ISSUE TITLE
Drop early always returns true

### ISSUE THREAD

**Issue by adeepkit01** [Vivek-anand-jain/ns3-aqm-blue#1]
I have always commented on the commit for this

**Comment by mohittahiliani** [comment]
@adeepkit01 - Can you provide the commit link?

**Comment by adeepkit01** [comment]
https://github.com/Vivek-anand-jain/ns3-aqm-blue/commit/fb9090b6e6530c2c40b2ca797a4e4c7a5c0e6aaf

The commit changed the function, earlier it was an if else ladder with default as return true, it was changed to a single if which returned true in if and also outside

**Comment by Vivek-anand-jain** [comment]
I have changed the code fr it. Please review it and let me know if we can close this issue.
