### ISSUE TITLE
Use of idle/m_idle?

### ISSUE THREAD

**Issue by adeepkit01** [Vivek-anand-jain/ns3-aqm-blue#2]
Check the commit comment

**Comment by mohittahiliani** [comment]
@adeepkit01 - Can you point me to that commit? Unable to locate it

**Comment by adeepkit01** [comment]
https://github.com/Vivek-anand-jain/ns3-aqm-blue/commit/57a6e9407463c05146aa6daa1558286e09f77db8

I commented here, but same goes for current m_idle variable
