### ISSUE TITLE
Possible redundancy 

### ISSUE THREAD

**Issue by adeepkit01** [Vivek-anand-jain/ns3-aqm-blue#9]
I feel that code from [here](https://github.com/Vivek-anand-jain/ns3-aqm-blue/blob/master/src/traffic-control/model/blue-queue-disc.cc#L211)  to [here](https://github.com/Vivek-anand-jain/ns3-aqm-blue/blob/master/src/traffic-control/model/blue-queue-disc.cc#L240) (Seems like a chunk, you directly brought forward from ns-2) is redundant because of [this](https://github.com/Vivek-anand-jain/ns3-aqm-blue/blob/master/src/traffic-control/model/blue-queue-disc.cc#L192) , both these are reactive queue full conditions. Do point out a case where these will be exclusive?

**Comment by mohittahiliani** [comment]
Done. Closing
